name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          working-directory: ${{ env.working-directory }}
          start: yarn start
          browser: chrome
